name: promptbench
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=1.3.0=py38h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - blas=1.0=mkl
  - blinker=1.4=py38h06a4308_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - click=8.0.4=py38h06a4308_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - flatbuffers=2.0.0=h2531618_0
  - flit-core=3.8.0=py38h06a4308_0
  - frozenlist=1.3.3=py38h5eee18b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h5eee18b_3
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.46.1=h33aed49_1
  - grpcio=1.42.0=py38hce63b2e_0
  - h5py=3.7.0=py38h737f45e_0
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - keras=2.11.0=py38h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.19.4=h568e23c_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.88.1=h91b91d3_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - markdown=3.4.1=py38h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - oauthlib=3.2.2=py38h06a4308_0
  - openssl=1.1.1t=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.0=py38h06a4308_0
  - pip=23.0.1=py38h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38h06a4308_0
  - pyopenssl=23.0.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.10.1=py38h14f4228_0
  - setuptools=65.6.3=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.41.1=h5eee18b_0
  - tensorboard=2.11.0=py38h06a4308_0
  - tensorboard-data-server=0.6.1=py38h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py38h06a4308_0
  - tensorflow=2.11.0=mkl_py38hda6d4db_0
  - tensorflow-base=2.11.0=mkl_py38he5f8e37_0
  - tensorflow-estimator=2.11.0=py38h06a4308_0
  - termcolor=2.1.0=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - urllib3=1.26.15=py38h06a4308_0
  - werkzeug=2.2.3=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - accelerate==0.18.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anytree==2.8.0
      - attrs==22.2.0
      - beautifulsoup4==4.12.0
      - bert-score==0.3.13
      - bitsandbytes==0.38.1
      - bpemb==0.3.4
      - cchardet==2.1.7
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - cloudpickle==2.2.1
      - cmake==3.26.1
      - conllu==4.5.2
      - contourpy==1.0.7
      - cycler==0.11.0
      - datasets==2.4.0
      - deprecated==1.2.13
      - dill==0.3.5.1
      - docopt==0.6.2
      - editdistance==0.6.2
      - einops==0.6.1
      - evaluate==0.4.0
      - filelock==3.10.6
      - flair==0.11.3
      - fonttools==4.39.2
      - fsspec==2023.3.0
      - ftfy==6.1.1
      - future==0.18.3
      - gdown==4.4.0
      - gensim==4.3.1
      - huggingface-hub==0.14.1
      - hyperopt==0.2.7
      - importlib-metadata==3.10.1
      - importlib-resources==5.12.0
      - janome==0.4.2
      - jieba==0.42.1
      - jinja2==3.1.2
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - konoha==4.6.5
      - langdetect==1.0.9
      - language-tool-python==2.7.1
      - lemminflect==0.2.3
      - lit==16.0.0
      - lru-dict==1.1.8
      - lxml==4.9.2
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - more-itertools==9.1.0
      - mpld3==0.3
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.13
      - networkx==3.0
      - nltk==3.8.1
      - num2words==0.5.12
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - openai==0.27.2
      - openhownet==2.0
      - overrides==3.1.0
      - pandas==1.5.3
      - pillow==9.4.0
      - pinyin==0.4.0
      - pptree==3.1
      - protobuf==4.22.1
      - psutil==5.9.4
      - py4j==0.10.9.7
      - pyarrow==11.0.0
      - pycld2==0.41
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.2
      - pyyaml==6.0
      - regex==2023.3.23
      - requests==2.28.2
      - responses==0.18.0
      - scikit-learn==1.2.2
      - segtok==1.5.11
      - sentencepiece==0.1.95
      - smart-open==6.3.0
      - soupsieve==2.4
      - sqlitedict==2.1.0
      - sympy==1.11.1
      - tabulate==0.9.0
      - tensorflow-hub==0.13.0
      - terminaltables==3.1.10
      - textattack==0.3.8
      - threadpoolctl==3.1.0
      - tokenizers==0.13.2
      - torch==2.0.0
      - tqdm==4.65.0
      - transformers==4.31.1
      - triton==2.0.0
      - typing-extensions==4.5.0
      - wcwidth==0.2.6
      - wikipedia-api==0.5.8
      - word2number==1.1
      - wrapt==1.15.0
      - xxhash==3.2.0
      - yarl==1.8.2
      - zipp==3.15.0
prefix: /anaconda/envs/promptbench
